addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.1")
addSbtPlugin("io.taig" % "sbt-houserules" % "0.11.5")
addSbtPlugin("io.taig" % "sbt-blowout-yaml-circe" % "0.2.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.19.0")
